spring.application.name=expense-management

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/ExpenseManagement
spring.datasource.username=postgres
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML
spring.thymeleaf.suffix=.html
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.enabled=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_APP_USERNAME}
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

google_access_token_url=https://www.googleapis.com/oauth2/v4/token
google_user_info_url=https://www.googleapis.com/oauth2/v3/userinfo
google_client_id=${google_clientId}
google_client_secret=${google_clientSecret}

signerKey=${SIGNER_KEY}